### ISSUE TITLE
Incoming twitch chat does work

### ISSUE THREAD

**Issue by foxreinhold** [TabletopsAndAnvils/Foundry-Stream-Module#7]
Love the mod, and the new version looks the best, but incoming twitch chat does not work.  Everything else does including dice rolls, dice roll requests, outgoing twitch chat using /t, and DSN support.  Even on a fresh world, it won't take incoming chat but everything else works.  Here's the error that's popping up in Chrome in case it helps!

Thanks for the mod!

![Screenshot 2021-04-22 003821](https://user-images.githubusercontent.com/77173822/115656332-13f53b00-a303-11eb-9c61-8d3bd90f896b.jpg)

**Comment by TabletopsAndAnvils** [comment]
The first error is actually just because the module is looking for something before it exists, happens every time it loads. The second in the list is another one of those type of errors, at least that's where I've always seen the CORS message appear, but again, it shouldn't be anything to worry about and not the cause of the issue, just Twitch saying "you can't access this right now". The last one I've never seen before, appears to be user specific. Also strange because FSM doesn't access the Twitch api directly and uses the tmi.js library instead.  Let me see what I can dig up in the morning.

**Comment by TabletopsAndAnvils** [comment]
Did some tracking on the last error you got (api.twitch.tv/kraken etc) and I've tracked it down to looking for custom emoticon set for your channel so that can't be the issue either. First thing I would check is use a different Twitch account than the one configured in the module to test the chat from the Twitch side of things. In order to remove echoing of messages sent from Foundry to Twitch the module looks at your user name and ignores them coming from Twitch. ie, if your username is BobBot, and a message goes from Foundry it will show up in Twitch as "BobBot: [Gronk the Destroyer]: Test" - the module will see it's own message when it appears but since it would be redundant to create a chat card for it again it just ignores anything on the Twitch chat coming rom BobBot.

**Comment by foxreinhold** [comment]
So I think the problem was that I was testing it with an account called "NotFoxReinhold" which it was still seeing as FoxReinhold...  One of the players just popped in and tried it and it worked perfectly.  Thank you for your help and sorry that it was something so silly.
